### ISSUE TITLE
Add padding to end of the clips.

### ISSUE THREAD

**Issue by QiLinXue** [jonah-chen/midi-shark#19]
Songs are divided into 20s intervals. The last clip of a song can be below 20s. There are two ways to deal with it.

* Ignore it (currently doing, but may cause issues with the model being "bad" for ending clips)
* Add Padding.

I can edit the code to add padding, what do you think? Is this important enough?

**Comment by jonah-chen** [comment]
Given that we are training the dataset as an unbiased dataset (since we aren't planning to manually weigh the loss on each sample), we are already assuming that the start and end of the song are "similar enough".

However, you have a point there. In real life, there will be clips you have to transcribe that are shorter than 20s (or whatever your window is). A possible data augmentation method is to remove part of the data at the end.

If it is easy to include, you should have `pad_end` as an optional argument that defaults to false. Otherwise, don't worry about it for now.

**Comment by QiLinXue** [comment]
ignored
